const Router = require('express')
const router = new Router()
const accountDataRouter = require('./accountDataRouter')
const calendarRouter = require('./calendarRouter')
const dataTypeRouter = require('./dataTypeRouter')
const departmentRouter = require('./departmentRouter')
const messageRouter = require('./messageRouter')
const messageTypeRouter = require('./messageTypeRouter')
const reworkingMonthRouter = require('./reworkingMonthRouter')
const reworkingRouter = require('./reworkingRouter')
const typeOfWorkRouter = require('./typeOfWorkRouter')
const typeOverUnderWorkRouter = require('./typeOverUnderWorkRouter')
const underworkingMonthRouter = require('./underworkingMonthRouter')
const underworkingRouter = require('./underworkingRouter')
const userRoleRouter = require('./userRoleRouter')
const userRouter = require('./userRouter')
const workflowTimeTypeRouter = require('./workflowTimeTypeRouter')
const workingHoursRouter = require('./workingHoursRouter')
const writingOffTimeRouter = require('./writingOffTimeRouter')

const otchetController = require('../controllers/otchetController')

router.use(process.env.DB_SERVER_ACCOUNT_DATA, accountDataRouter)
router.use(process.env.DB_SERVER_CALENDAR, calendarRouter)
router.use(process.env.DB_SERVER_DATA_TYPE, dataTypeRouter)
router.use(process.env.DB_SERVER_DEPARTMENT, departmentRouter)
router.use(process.env.DB_SERVER_MESSAGE, messageRouter)
router.use(process.env.DB_SERVER_MESSAGE_TYPE, messageTypeRouter)
router.use(process.env.DB_SERVER_REWORKINGS_MONTH, reworkingMonthRouter)
router.use(process.env.DB_SERVER_REWORKINGS, reworkingRouter)
router.use(process.env.DB_SERVER_TYPE_OF_WORK, typeOfWorkRouter)
router.use(process.env.DB_SERVER_TYPE_OVER_UNDER_WORK, typeOverUnderWorkRouter)
router.use(process.env.DB_SERVER_UNDERWORKINGS_MONTH, underworkingMonthRouter)
router.use(process.env.DB_SERVER_UNDERWORKINGS, underworkingRouter)
router.use(process.env.DB_SERVER_USER_ROLE, userRoleRouter)
router.use(process.env.DB_SERVER_USER, userRouter)
router.use(process.env.DB_SERVER_WORKFLOW_TIME_TYPE, workflowTimeTypeRouter)
router.use(process.env.DB_SERVER_WORKINGS_HOURS, workingHoursRouter)
router.use(process.env.DB_SERVER_WRITTEN_OFF_TIME, writingOffTimeRouter)

router.get(process.env.DB_SERVER_OTCHET, otchetController.getOtchet)

module.exports = router