const Router = require('express')
const router = new Router()
const accountDataRouter = require('./accountDataRouter')
const calendarRouter = require('./calendarRouter')
const dataTypeRouter = require('./dataTypeRouter')
const departmentRouter = require('./departmentRouter')
const messageRouter = require('./messageRouter')
const messageTypeRouter = require('./messageTypeRouter')
const reworkingMonthRouter = require('./reworkingMonthRouter')
const reworkingRouter = require('./reworkingRouter')
const typeOfWorkRouter = require('./typeOfWorkRouter')
const typeOverUnderWorkRouter = require('./typeOverUnderWorkRouter')
const underworkingMonthRouter = require('./underworkingMonthRouter')
const underworkingRouter = require('./underworkingRouter')
const userRoleRouter = require('./userRoleRouter')
const userRouter = require('./userRouter')
const workflowTimeTypeRouter = require('./workflowTimeTypeRouter')
const workingHoursRouter = require('./workingHoursRouter')
const writingOffTimeRouter = require('./writingOffTimeRouter')

const otchetController = require('../controllers/otchetController')

router.use('/accountdata', accountDataRouter)
router.use('/calendar', calendarRouter)
router.use('/datatype', dataTypeRouter)
router.use('/department', departmentRouter)
router.use('/message', messageRouter)
router.use('/messagetype', messageTypeRouter)
router.use('/reworkingmonth', reworkingMonthRouter)
router.use('/reworking', reworkingRouter)
router.use('/typeofwork', typeOfWorkRouter)
router.use('/typeoverunderwork', typeOverUnderWorkRouter)
router.use('/underworkingmonth', underworkingMonthRouter)
router.use('/underworking', underworkingRouter)
router.use('/userrole', userRoleRouter)
router.use('/user', userRouter)
router.use('/workflowtimetype', workflowTimeTypeRouter)
router.use('/workinghours', workingHoursRouter)
router.use('/writtenofftime', writingOffTimeRouter)

router.get('/otchet', otchetController.getOtchet)

module.exports = router